### ISSUE TITLE
Apple system, error reported：use of undeclared identifier 'FLTPDFViewFlutterPlugin'。info.plist configured

### ISSUE THREAD

**Issue by vhgdqm** [endigo/flutter_pdfview#99]

**Comment by philiplindberg** [comment]
Seeing this too. Works fine on Android, v1.0.3+8 doesn't compile on iOS.

Did some testing, seems like versions prior to 1.0.0+11 compile on both iOS and Android.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-US)
    • Flutter version 1.22.3 at /Users/philiplindberg/Code/flutter
    • Framework revision 8874f21e79 (4 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/philiplindberg/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/philiplindberg/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0


[✓] Connected device (2 available)
    • Pixel 3 (mobile)         • 96KX221LS                 • android-arm64 • Android 11 (API 30)
    • Philip's iPhone (mobile) • 00008020-00151D9C3682002E • ios           • iOS 14.2

• No issues found!
```

</details>

**Comment by PlacidoLv** [comment]
me too
